version: 2
updates:
  # Enable version updates for npm (if you have a Node.js project)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "teamapollogit"
    assignees:
      - "teamapollogit"
    commit-message:
      prefix: "npm"
      include: "scope"

  # Enable version updates for pip (if you have a Python project)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "teamapollogit"
    assignees:
      - "teamapollogit"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Enable version updates for bundler (if you have a Ruby project)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "teamapollogit"
    assignees:
      - "teamapollogit"
    commit-message:
      prefix: "bundler"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "teamapollogit"
    assignees:
      - "teamapollogit"
    commit-message:
      prefix: "actions"
      include: "scope"

  # Enable version updates for Docker (if you have Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "teamapollogit"
    assignees:
      - "teamapollogit"
    commit-message:
      prefix: "docker"
      include: "scope"